Models/PreguntasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CampingHalconMVC.Models
{
    public class PreguntasController : Controller
    {
        // GET: Preguntas
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampingHalconMVC.Models;

namespace CampingHalconMVC.Controllers
{
    public class CarritoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Carrito
        public ActionResult Index()
        {
            string email = User.Identity.Name;
            var carritoModel = db.Carritos.FirstOrDefault(c => c.Creador == email);
            if (carritoModel == null)
            {
                return RedirectToAction("Index", "Categoria", null);
            }
            return View(carritoModel);
        }

        // GET: Carrito/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarritoModel carritoModel = db.Carritos.Find(id);
            if (carritoModel == null)
            {
                return HttpNotFound();
            }
            return View(carritoModel);
        }

        // GET: Carrito/AddProduct/1
        public ActionResult AddProduct(int? id)
        {
            string email = User.Identity.Name;
            var carritoModel = db.Carritos.FirstOrDefault(c => c.Creador == email);
            if (carritoModel == null)
            {
                carritoModel = new CarritoModel()
                {
                    Creador = email
                };
                db.Carritos.Add(carritoModel);
            }
            //if (!carritoModel.Productos.Any(p => p.Id == id))
            //{
            //    carritoModel.Productos.Add(db.Productos.Find(id));
            //}
            carritoModel.Productos.Add(db.Productos.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Carrito/DelProduct/1
        public ActionResult DelProduct(int? id)
        {
            string email = User.Identity.Name;
            var carritoModel = db.Carritos.FirstOrDefault(c => c.Creador == email);
            if (carritoModel.Productos.Any(p => p.Id == id))
            {
                carritoModel.Productos.Remove(db.Productos.Find(id));
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ProductoController.cs
using CampingHalconMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CampingHalconMVC.Controllers
{
    public class ProductoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Producto/Buscar
        public ActionResult Buscar(List<ProductoModel> productoModels)
        {
            return View(productoModels);
        }

        // POST: Producto/Buscar
        [HttpPost]
        public ActionResult Buscar(string parametro)
        {
            var productoModels = db.Productos.Where(p => p.Nombre.Contains(parametro)).ToList();
            return View(productoModels);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <style>
        body {
            background-image: url(/Content/imgPrueba/fondo1.jpg);
        }
    </style>
</head>
<body>
    <div class="container" style="background-color: white">

        <!--Prueba de contenedor con texto-->
        <!--***************************************************************************************************************************-->
        <div class="container" style="width:100%; margin-top:20px; ">


            <div class="container" style="width:100%; margin-top:20px; ">
                <img src="~/Content/imgPrueba/logo1.jpg" width="100" height="100" />
                <div class="titulo">
                    <div class="contenedor"><b style="font-family:'Brush Script MT'; font-size:300%; color:black;">Camping-Halcón</b></div>
                    <br />
                    <div class="contenedor"><b style="font-family:'Brush Script MT'; font-size:200%; color:black;">Slogan</b></div>
                </div>
                @if (!Request.IsAuthenticated)
                {
                    <div class="titulo2">
                        @Html.ActionLink("Iniciar sesión", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "btn btn-default" })
                        <a href="@Url.Action("Index", "Carrito", null)">

                            <img src="~/Content/imgPrueba/carrito.png" style="margin-left: 30px;" width="50" height="50" />
                            <div class="contador-carrito">@CampingHalconMVC.Models.CarritoModel.ContadorProductos(User.Identity.Name)</div>
                        </a>
                    </div>
                }
                else
                {
                    <div class="titulo2">
                        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            @Html.AntiForgeryToken()
                            <a class="btn btn-default" type="button" style="background-color:white;" href="javascript:document.getElementById('logoutForm').submit()">Cerrar Sesión</a>
                            <a href="@Url.Action("Index", "Manage", null)"><img src="~/Content/imgPrueba/user.png" style="margin-left: 30px;" width="50" height="50 " /></a>

                            <a href="@Url.Action("Index", "Carrito", null)">

                                <img src="~/Content/imgPrueba/carrito.png" style="margin-left: 30px;" width="50" height="50" />
                                <div class="contador-carrito">@CampingHalconMVC.Models.CarritoModel.ContadorProductos(User.Identity.Name)</div>
                            </a>


                        }

                    </div>
                }

            </div>



            <style>
                .contador-carrito {
                    position: absolute;
                    top: -5px;
                    right: 15px;
                    color: black;
                    font-size: 18px;
                }

                .contenedor-carrito {
                    position: relative;
                    text-align: center;
                    color: white;
                }

                .contenedor {
                    position: relative;
                    display: inline-block;
                    text-align: center;
                }

                .contenedor2 {
                    position: relative;
                    display: inline-block;
                }


                .centrado {
                    position: absolute;
                    top: 50%;
                    left: 50%;
                    transform: translate(-50%, -50%);
                }

                .centrado2 {
                    position: absolute;
                    top: 70%;
                    left: 50%;
                    transform: translate(-50%, -50%);
                }

                .titulo {
                    position: absolute;
                    display: inline-block;
                }

                .titulo2 {
                    position: absolute;
                    display: inline-block;
                    left: 65%;
                    top: 12%;
                }
            </style>
            <!--***************************************************************************************************************************-->
            <!---->
            <br />
            <div class="navbar navbar-inverse ">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">

                        </a>
                        @Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                @Html.ActionLink("Categorias", "Index", "Categoria", new { area = "" }, new { @class = "navbar-brand" })
                                @Html.ActionLink("Preguntas Frecuentes", "Index", "Preguntas", new { area = "" }, new { @class = "navbar-brand" })
                            </li>
                        </ul>
                    </div>

                </div>
            </div>
                @using (Html.BeginForm("Buscar", "Producto", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="container">
                        <table>
                            <tr>
                                <td style="background-color:gray"><div class="input-group mb-3"><input name="parametro" type="text" class="form-control" placeholder="" aria-label="Username" aria-describedby="basic-addon1"></div></td>
                                <td><div><button type="submit" class="btn btn-primary; " style=" background-color: darkolivegreen ">  Buscar </button></div></td>

                            </tr>
                        </table>
                    </div>
                }
            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <div class="container" style="background-color: white ">
                        <p style="color:white;">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                        <p style="color:white;">hola</p>

                    </div>

                </footer>
            </div>




        </div>
    </div>
    <div class="container" style="background-color: #232120;">
        <div class="contenedor2">

            <p style="color:white; font-size:100%; ">Contactanos: </p>
            <p style="color:white;">
                Av. Universidad 1200, Col. Xoco, Ciudad de México, Alcaldía Benito Juárez C.P. 03330 <br />
                Tel: 123456789 <br />
                Email: contacto@tecnm.m
            </p>
            <p style="color:white;">
                Redes sociales:
            </p>

            <div>
                <div class="contenedor">
                    <img src="~/Content/imgPrueba/f.png" width="50" height="50" />

                </div>

                <div class="contenedor">
                    <img src="~/Content/imgPrueba/t.png" width="50" height="50" />

                </div>
                <div class="contenedor">
                    <img src="~/Content/imgPrueba/i.png" width="50" height="50" />

                </div>


            </div>

            <p style="color:white;">&copy; @DateTime.Now.Year - Equipo 4</p>
        </div>

        <div class="contenedor">

            <p style="color: #232120;">
                Av. Universidad 1200, Col. Xoco, Ciuda
            </p>
        </div>

        <div class="titulo">
            <div>
                <div class="contenedor">
                    <img src="~/Content/imgPrueba/logo1.jpg" width="80" height="80" />


                    <div class="contenedor" style="margin-left: 30px;">
                        <br />
                        <br />
                        <p style="color:white;">Tarjetas:</p>
                        <div class="contenedor">
                            <img src="~/Content/imgPrueba/tarjeta1.png" width="50" height="50" />

                        </div>
                        <div class="contenedor">
                            <img src="~/Content/imgPrueba/tarjeta2.png" width="50" height="50" />

                        </div>

                    </div>
                </div>

            </div>
            <br />
            <br />

            <p style="color:white;">
                Instituto Tecnologico de Toluca, E-commerce 2022
            </p>

        </div>



    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>